require.config({ 
	baseUrl:'../static/js/libs', 
	paths:{ 
		jquery:'jquery.min', 
		underscore:'underscore', 
		jsonjs:'json', 
		md5:'md5', 
		common:'common' 
	}, 
	shim:{ 
		underscore:{ 
			exports:'_' 
		}, 
		jsonjs:{
			deps:['jquery']
		} 
	} 
});

require(['jquery','underscore','common','jsonjs','md5'],function($,_,common){
});
